= DEMO RH-FORUM

== Preparação

=== Abrir slides

.Linux

  google-chrome --incognito https://docs.google.com/presentation/d/1ptT_15EFnNV2098e13BEa99yJJkS94aUadhcFVD6PN4 &

.Mac

  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome https://docs.google.com/presentation/d/1ptT_15EFnNV2098e13BEa99yJJkS94aUadhcFVD6PN4

=== Clonar repositório

  git clone git@github.com:redhat-sas-middleware-brazil/demo-howtos.git && cd demo-howtos/rh-forum-2017

=== Iniciar o docker

  systemctl start docker

WARNING: Caso você use algum clipboard manager, limpe-o para evitar mostrar dados indevidos

=== Baixe a linha de comando do Openshift

Download[https://github.com/openshift/origin/releases]

=== Limpar projetos no Openshift do Google Cloud:

 * rhforum-app-dev
 * rhforum-app-prod

Abra a console https://console.ocp.rhbrlab.com:8443[https://console.ocp.rhbrlab.com:8443]

(?) -> Command Line Tools

  oc login https://console.ocp.rhbrlab.com:8443 --token=<pegar_da_console_web>
  oc delete all --all -n rhforum-app-dev && oc delete all --all -n rhforum-app-prod

[WARN]
====
Garanta que o container do Jenkins esteja rodando antes de executar o próximo comando. Para isso, faça:
====

  oc scale dc jenkins --replicas=1 -n cicd-tools

Apague o pipeline do projeto cicd-tools

  oc delete bc rhforum-pipeline -n cicd-tools

=== Deletar repo no gogs

  google-chrome --incognito https://gogs.apps.ocp.rhbrlab.com/ &

=== Abrir janelas de todos os projetos

.Linux

  google-chrome --incognito https://console.ocp.rhbrlab.com:8443 &
  google-chrome --incognito http://sonar.apps.ocp.rhbrlab.com/ &
  google-chrome --incognito https://jenkins-cicd-tools.apps.ocp.rhbrlab.com/ &
  google-chrome --incognito http://nexus.apps.ocp.rhbrlab.com/ &
  google-chrome --incognito https://gogs.apps.ocp.rhbrlab.com/ &

.Mac

  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --incognito https://console.ocp.rhbrlab.com:8443 & \
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --incognito http://sonar.apps.ocp.rhbrlab.com/ & \
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --incognito https://jenkins-cicd-tools.apps.ocp.rhbrlab.com/ & \
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --incognito http://nexus.apps.ocp.rhbrlab.com/ & \
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --incognito https://gogs.apps.ocp.rhbrlab.com/

=== Logar no Gogs
=== Abrir JBDS 11 e iniciar forge (Ctrl + Shift 4)
=== Limpar as configurações do Openshift

Digitar no console do Forge para limpar as configurações (*SOMENTE SE NUNCA TIVER INSTALADO - SÓ NA PRIMEIRA VEZ*)

[source,bash]
rm -rf ~/.forge
addon-install-from-git --url https://github.com/forge/wildfly-swarm-addon.git
addon-install-from-git --url https://github.com/guaxinim/swagger-addon.git
addon-install-from-git --url https://github.com/guaxinim/forge-plugin-gitignore.git
addon-install --coordinate io.fabric8.forge:devops,2.3.90
addon-install --coordinate io.fabric8.forge:kubernetes,2.3.90
rm -rf ~/.gitignore_boilerplate

== Apresentação

=== Criação da aplicação com o Forge no JBoss Developer Studio

[source,bash]
----
# Cria novo projeto
project-new --named rhforum --version 1.0 --stack JAVA_EE_7 --type wildfly-swarm --top-level-package com.redhat.rhforum

# Configura git
git-setup
gitignore-setup <1>
gitignore-create --templates Maven

# Criar entidade JPA
jpa-new-entity --named Cliente
jpa-new-field --named nome
jpa-new-field --named sobrenome

# Adiciona Bean Validation
wildfly-swarm-add-fraction --fractions bean-validation
constraint-add --constraint NotNull --on-property nome
constraint-add --constraint NotNull --on-property sobrenome

# Adiciona datasource
wildfly-swarm-add-fraction --fractions datasources
jdbc-add-dependency --db-type H2 --version 1.4.196

# Gera endpoint REST a partir da entidade JPA
rest-generate-endpoints-from-entities --targets com.redhat.rhforum.model.Cliente

# Adiciona swagger
wildfly-swarm-add-fraction --fractions swagger
swagger-setup
swagger-generate

# Adiciona testes
wildfly-swarm-new-test --named ClienteTest

# Adiciona contexto de health check
wildfly-swarm-add-fraction --fractions monitor

# Gera classe main
wildfly-swarm-detect-fractions --depend
wildfly-swarm-new-main-class
----
<1> apenas se for a primeira vez!!!

[NOTE]
======
O Forge não cria os testes unitários do CRUD. Caso queira adicionar na mão...
Abra a classe `ClienteTest.java` gerada pelo Forge e adicionar o trecho abaixo no corpo da classe:

[source,java]
--
@Inject
ClienteEndpoint clienteService;

@Test
public void should_start_service() {
}

@Test
public void testGetClientes() {
  List<Cliente> clientes = clienteService.listAll(0, 10);

  assertTrue(clientes.size() > 0);

  for (Cliente cliente : clientes) {
    System.out.println("Cliente: " + cliente.getNome() + " " + cliente.getSobrenome());
  }
}
--
======

#### Executar o build maven

[source,bash]
----
cd $WORKSPACE_DIR/rhforum
mvn clean package -DskipTests=true
----

### Executar a aplicação

[source,bash]
----
java -jar -Dswarm.context.path=/rhforum target/rhforum-swarm.jar
----

#### Abrir aplicação no browser:

[source,bash]
----
google-chrome --incognito http://127.0.0.1:8080/rhforum/apidocs &
----

##### Ver clientes

[source,bash]
----
http http://127.0.0.1:8080/rhforum/rest/clientes
----

##### Criar cliente

[source,bash]
----
# Criar cliente gustavo
http http://127.0.0.1:8080/rhforum/rest/clientes nome=gustavo sobrenome=luszczynski

# Criar cliente elvis
http http://127.0.0.1:8080/rhforum/rest/clientes nome=elvis sobrenome=morreu
----

##### Atualizar cliente

[source,bash]
----
# Atualizar cliente elvis
http put http://127.0.0.1:8080/rhforum/rest/clientes/2 id=2 nome=elvis sobrenome=naomorreu version=0
----

##### Deletar cliente

[source,bash]
----
# Deletar cliente elvis
http DELETE http://127.0.0.1:8080/rhforum/rest/clientes/2
----

##### Mostrar heath check do swarm

[source,bash]
----
# Ver metricas do node
http http://localhost:8080/node

# Ver metricas do heap
http http://localhost:8080/heap
----

##### Derrubar o wildfly-swarm

`Ctrl + c`

#### Rodar Openshift local

  oc cluster up --version=v3.6.173.0.5

ou

  minishift start

##### Abrir console

https://127.0.0.1:8443[https://127.0.0.1:8443]

#### Preparar para deploy no Openshift

Adicionar plugins no espaço depois de </plugin>

Plugins a serem adicionado no pom.xml
[source,xml]
  <plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>fabric8-maven-plugin</artifactId>
    <version>3.1.92</version>
    <executions>
      <execution>
        <goals>
          <goal>resource</goal>
          <goal>build</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <resources>
        <env>
          <JAVA_OPTIONS>-Djava.net.preferIPv4Stack=true -Dswarm.context.path=/rhforum</JAVA_OPTIONS>
        </env>
      </resources>
      <generator>
        <includes>
          <include>wildfly-swarm</include>
        </includes>
      </generator>
    </configuration>
  </plugin>
  <plugin>
    <groupId>com.lazerycode.jmeter</groupId>
    <artifactId>jmeter-maven-plugin</artifactId>
    <version>2.2.0</version>
    <executions>
      <execution>
          <id>jmeter-tests</id>
          <goals>
              <goal>jmeter</goal>
          </goals>
      </execution>
    </executions>
    <configuration>
      <propertiesGlobal>
          <threads>10</threads>
          <testIterations>5</testIterations>
      </propertiesGlobal>
    </configuration>
  </plugin>
  <plugin>
    <groupId>com.restlet.dhc</groupId>
    <artifactId>dhc-maven-plugin</artifactId>
    <version>1.4.1</version>
    <executions>
      <execution>
        <id>default-cli</id>
        <goals>
          <goal>help</goal>
        </goals>
        <configuration>
          <file>src/test/integration/integration-rest.json</file>
        </configuration>
      </execution>
    </executions>
  </plugin>

Repositorio adicional para o plugin `dhc-maven-plugin`

[source,xml]
<pluginRepositories>
  <pluginRepository>
    <id>boundlessgeo</id>
    <url>http://repo.boundlessgeo.com/main</url>
  </pluginRepository>
</pluginRepositories>

Criar __Fabric8 Resource Fragment__ para incluir a variável `JAVA_OPTIONS` no `DC`

[source,bash]
--
mkdir -p src/main/fabric8 && cat << 'EOF' > src/main/fabric8/deployment.yml

spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: '-Djava.net.preferIPv4Stack=true -Dswarm.context.path=/rhforum'
EOF
--

Copiar arquivos

* Abrir o Terminal e copiar os arquivos do jmeter e do test da API

[source,bash]
--
REPO_DIR=/home/gustavo/github/demo-howtos
WORKSPACE_DIR=/home/[user]/[jbds_workspace]

cp -r $REPO_DIR/rh-forum-2017/config/tests/* $WORKSPACE_DIR/rhforum/src/test
cp $REPO_DIR/rh-forum-2017/config/nexus_openshift_settings.xml $WORKSPACE_DIR/rhforum/nexus_openshift_settings.xml
cp $REPO_DIR/rh-forum-2017/config/Jenkinsfile $WORKSPACE_DIR/rhforum/Jenkinsfile
--

[NOTE]
====
$REPO_DIR equivale ao diretorio onde você fez o clone do github.
Exemplo: /home/[user]]/github/demo-howtos

$WORKSPACE_DIR equivale ao diretório do seu eclipse/JBDS
Exemplo:
/home/[user]/[jbds_workspace]
====

#### Deploy da app no Openshift
[source,bash]
--
cd $WORKSPACE_DIR/rhforum

mvn -X clean fabric8:deploy -Dfabric8.deploy.createExternalUrls=true -DskipTests
--

contexto: */rhforum*

##### Acessar a aplicação:

http://rhforum.app.127.0.0.1.nip.io/rhforum/apidocs[http://rhforum.app.127.0.0.1.nip.io/rhforum/apidocs]

##### Mostrar console do Openshift

##### Conectar no Openshift via JBDS (usuario: developer)

* Mostrar Pod Logging
* Mostrar Port Forward
* Criar um Postgres via JBDS

### Openshift no GCE (Produção)

Criar repo no gogs

Abrir gogs e criar repositório rhforum

Adicionar repo remoto

[source,bash]
cd $REPO_DIR
git add .
git commit -m "first commit"
git remote add origin http://gogs.apps.ocp.rhbrlab.com/gustavo/rhforum.git
git push -u origin master

Adicionar pipeline no projeto CI-CD Tools (Google Cloud)

*OBS: Modificar o nome do pipeline abaixo e a URI do Git.*
[source,yaml]
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "cicd-tools",
      "kind": "DeploymentConfig"}]'
  name: roadshow-pipeline <1>
spec:
  source:
    git:
      ref: master
      uri: http://gogs.apps.ocp.rhbrlab.com/elvis/rhforum.git <2>
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline

<1> Alterar de acordo com ambiente
<2> Alterar para o repositório recém criado

#### Executar Pipeline
#### Ver Rollout com nova versao

{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +
{nbsp} +

'''


TODOS:

* https://blog.openshift.com/fast-iterative-java-development-on-openshift-kubernetes-using-rsync/
* https://developers.redhat.com/blog/?p=438229
* https://developers.redhat.com/blog/2017/04/28/using-jboss-datagrid-in-openshift-paas/
* https://blog.openshift.com/debugging-java-applications-on-openshift-kubernetes/
